### PR TITLE
Fix UX

### LINKED ISSUE #31: "Enter" button to login
After paste or inputting the passphrase, please allow Enter button to work for "Login". Rather than clicking. At the moment Enter key just creates a new paragraph or goes to the next row.

### PR DESCRIPTION
**Pull request by Kiruel**

### CODE REVIEW

**Comment by ca333** [comment]
@buildog - Kiruel is senior mobile (GUI) developer at Monaize
his PR closes https://github.com/buildog/BarterDEX/issues/31

**Comment by Kiruel** [comment]
@buildog i fix the #30 on my last commit

**Comment by buildog** [comment]
merci @Kiruel !

**Comment by Kiruel** [comment]
No problem :)

**Pull request merged**
